### ISSUE TITLE
[CLI] No recovery from a file not found

### ISSUE THREAD

**Issue by mhogerheijde** [pomber/git-history#106]
When showing the history of a file, going to a commit where that file didn't exist (yet), shows a "file not found", but no other interfacing to get back to where you came from.

![screenshot from 2019-02-22 15-28-24](https://user-images.githubusercontent.com/1466140/53248684-97c92380-36b6-11e9-8b23-e66ec3e20e53.png)

It is accompanied with the following error message:

```
Server error { Error: Command failed: git show cfb86c85:./Helper.scala
fatal: Path 'generator-maven-plugin/src/main/scala/nl/ebpi/husky/mavenplugin/Helper.scala' exists on disk, but not in 'cfb86c85'.

    at makeError (/home/mhogerheijde/.nvm/versions/node/v8.4.0/lib/node_modules/git-file-history/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/mhogerheijde/.nvm/versions/node/v8.4.0/lib/node_modules/git-file-history/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 128,
  stdout: '',
  stderr: 'fatal: Path \'generator-maven-plugin/src/main/scala/nl/ebpi/husky/mavenplugin/Helper.scala\' exists on disk, but not in \'cfb86c85\'.\n',
  failed: true,
  signal: null,
  cmd: 'git show cfb86c85:./Helper.scala',
  timedOut: false,
  killed: false }
Let us know of the error at https://github.com/pomber/git-history/issues
```

**Comment by pomber** [comment]
Hey, thanks for reporting. What version of the CLI are you using? In the last version it shouldn't show commits where the file didn't exist. Or maybe is a commit where the file was deleted?

**Comment by mhogerheijde** [comment]
I installed today using `npm install -g`. I'm not at my (work) pc until Monday, so can't check it right now.

The file got added from a certain point in time and it has not been deleted since.

**Comment by mhogerheijde** [comment]
I'm using `0.1.0` on node `8.4.0`, but I also have the same on node `10.15.2` with `git-file-history@0.1.0`. It seems to be the latest version on npm currently.

**Comment by raviprakashgiri** [comment]
I'm having the same problem on node 11.9.0

**Comment by vntrungld** [comment]
I think this bug because you changed the target file name before. I'm facing this right now. Is there anyone know how to fix this?

**Comment by pomber** [comment]
Anyone have a public repo I can clone to reproduce this?
