### ISSUE TITLE
[VS Code] file path issue

### ISSUE THREAD

**Issue by black-jk** [pomber/git-history#95]
> `[2019-02-15 20:28:34.128] [exthost] [error] Error: ENOENT: no such file or directory, open '/c:/Users/xxxxx/.vscode/extensions/pomber.git-file-history-0.0.2/site/index.html'
	at Object.fs.openSync (fs.js:577:3)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
	at Object.fs.readFileSync (fs.js:483:33)
	at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:563:29)
	at c:\Users\xxxxx\.vscode\extensions\pomber.git-file-history-0.0.2\extension.js:44:24
	at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:485:959)
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:486:443)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:118)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:744)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:322)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:155)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:960
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:38:994
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20) extension.git-file-history`

'/c:/Users/xxxxx/.vscode/extensions/pomber.git-file-history-0.0.2/site/index.html'  -> wrong
'c:/Users/xxxxx/.vscode/extensions/pomber.git-file-history-0.0.2/site/index.html'  -> correct

**Comment by pomber** [comment]
Should have tested it on Windows. I'll publish the fix soon
